[build]
command = "npm run build"
functions = "netlify/functions"
publish = "build/client"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "build/client, max-age=31536000, s-maxage=31536000"
